version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bc
      POSTGRES_USER: bc
      POSTGRES_PASSWORD: bc
    volumes:
    - ./pg.sql:/docker-entrypoint-initdb.d/pg.sql
    networks:
      - app-network
  nodejs:
    image: neuralegion/brokencrystals
    container_name: nodejs
    restart: unless-stopped
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - web-root:/home/node/bc/public/build
  proxy:
    image: staticfloat/nginx-certbot
    restart: always
    environment:
      CERTBOT_EMAIL: "anatol@neuralegion.com"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html:ro
      - ./nginx-config:/etc/nginx/user.conf.d:ro
    depends_on:
      - nodejs
    networks:
      - app-network
volumes:
  web-root:
networks:
  app-network:
    driver: bridge
